import numpy as np
import pandas as pd
import pytest
from houseprice.config import TEST_DIR
from houseprice.data_management import clean_data

transliterate_mn
extract_price
drop_columns
rename_columns
replace_balcony_no
extract_and_convert_area
convert_column_to_string
replace_balcony_no
extract_balcony_numbers
filter_by_range
replace_flooring_material
replace_garage
replace_window_type
replace_door_type
replace_lease_type
clean_manual
